### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MinecraftGuy926** [Urokhtor/container-tooltips#2]
"Only show tooltip while crouched"

**Comment by Urokhtor** [comment]
I take that the motivation for key press activated tooltip is because the tooltip can feel obstructive?

Binding the tooltip to crouching could work. Although, I'm not sure if I want to bind the tooltip to an action in the game world. Another option would be to find a hotkey for triggering it. Shulker Box Tooltip mod uses Left Alt key to show full contents of the Shulker Box. Maybe binding the hotkey to Left Alt would work? It would be more aligned with Shulker Box Tooltip, and hopefully intuitive to use. Although I wonder how easy it is to press Left Alt when you are running around?

The hotkey behaviour should be configurable, so the players can choose whether they need always press the hotkey. Adding support for Cloth Config would make it easier to add other configurations in the future as well.

**Comment by Urokhtor** [comment]
Actually, Shulker Box Tooltip uses Left Shift to show the normal preview, which is also the default key Minecraft uses for crouching.

It was rather straightforward to implement this functionality with Cloth Config and Mod Menu. I added new configuration option `showAutomatically`, which is enabled by default which preserves the original functionality. If you want to be able to control when the tooltip is shown, you can toggle that setting off. Then the tooltip will be shown only when player presses the Left Shift key.

This functionality is now supported by 1.2.0 version of this mod.

**Comment by MinecraftGuy926** [comment]
Great work! I think this mod is going to be popular, it's very useful. I really appreciate your responsive development :)

**Comment by Urokhtor** [comment]
Thanks for the feedback! I usually have more time during weekends to concentrate on personal projects, so you got lucky I managed to add this feature before Monday.

**Comment by MinecraftGuy926** [comment]
Perfect timing then! Thanks again ;D
