### ISSUE TITLE
1.20.1 Left Alt for container search key

### ISSUE THREAD

**Issue by MinecraftGuy926** [Urokhtor/container-tooltips#4]
### I downloaded a repository and tried to change the keybind for container searches
![alt](https://github.com/user-attachments/assets/d4e36496-7a2f-4b2a-94c7-1c98f70210fc)

###  I did before a long time ago and it worked for me, but now I'm getting this and I don't know why.
![cctt](https://github.com/user-attachments/assets/559e4e40-184a-4f6f-b8e1-870507b0bc11)

Any ideas? Or maybe you can add a configurable keybind if thats possible. Cheers

**Comment by Urokhtor** [comment]
That warning just looks like IDEA warning that `PlayerRayCastClientMixin` is not referenced by any other class, but that is all right because IDEA does not know that it is loaded by Fabric through configuration.

**Comment by MinecraftGuy926** [comment]
### This also appears in IDEA
![contain](https://github.com/user-attachments/assets/5fdf1a1a-6fed-4f87-94f0-0697029eaeb2)
![container](https://github.com/user-attachments/assets/f2040f97-ce5a-402e-9a05-3cb961f6d6ff)

### All I have installed Fabric 1.20.1
![installed](https://github.com/user-attachments/assets/51c229e0-3dc4-4d81-b4dc-1e3f4dbf6164)

### The only thing I changed in the repos was that "(GLFW.GLFW_KEY_LEFT_ALT)" then I used "gradlew build." When I try to use my build the game crashes on launch

### crash report:
https://gist.github.com/MinecraftGuy926/c7662aa54cbb58b7c2c6e19f10e91c3f

**Comment by Urokhtor** [comment]
Not sure what's going on in there. The error indicates that Fabric can't find a core Minecraft class that should be there. As if the project was not built correctly. I checked the 1.20.1 branch locally and could build and run the game just fine, so that error looks weird.

However, I looked into making it possible to configure the key from mod menu, and decided to add this https://github.com/Urokhtor/container-tooltips/compare/main...configurable-tooltip-key

![image](https://github.com/user-attachments/assets/8858638f-0abd-4bc4-80fe-3cfa5ff5a59c)

I wanted to keep this simple, so the configuration does not use fancy ways to map text characters into input codes the game understands. This means you have to configure the actual GLFW input codes the game uses internally. In your case you want to use Left Alt key, so you need to use code 342. Full list of GLFW key mappings can be found [here](https://www.glfw.org/docs/3.3/group__keys.html).

Also, it is possible to configure other types of input, such as mouse keys. Full GLFW input reference with the mappings can be found [here](https://www.glfw.org/docs/3.4/group__input.html).

I'll try to get this feature released soon, so you won't have to build your own custom version of the mod anymore. :)

**Comment by Urokhtor** [comment]
It's released now. Hopefully this solves your problem.

**Comment by MinecraftGuy926** [comment]
Oh that's perfect! You're awesome!! Thank you very much :D
